export const CONFIG_PREFIX = 'nacos.discovery'

export const DISCOVERY_NACOS_OPTIONS = Symbol('DISCOVERY_NACOS_OPTIONS')
export const DISCOVERY_NACOS_ROOTOPTIONS = Symbol('DISCOVERY_NACOS_ROOTOPTIONS')
