export const CONFIG_PREFIX = 'nacos.config'

export const NACOS_DEFAULT_GROUP = 'DEFAULT_GROUP'

export const CONFIG_NACOS_OPTIONS = Symbol('CONFIG_NACOS_OPTIONS')
export const CONFIG_NACOS_ROOTOPTIONS = Symbol('CONFIG_NACOS_ROOTOPTIONS')
