export const CONFIG_PREFIX = 'http'

export const HTTP_OPTIONS = Symbol('HTTP_OPTIONS')
export const AXIOS_INSTANCE = Symbol('AXIOS_INSTANCE')

export const REQUEST_PATH_METADATA = 'REQUEST_PATH_METADATA'
export const REQUEST_METHOD_METADATA = 'REQUEST_METHOD_METADATA'
export const REQUEST_OPTIONS_METADATA = 'REQUEST_OPTIONS_METADATA'

export const PARAMETER_METADATA = 'PARAMETER_METADATA'
export const PARAMETER_BODY_METADATA = 'PARAMETER_BODY_METADATA'
export const PARAMETER_QUERY_METADATA = 'PARAMETER_QUERY_METADATA'
export const PARAMETER_PARAM_METADATA = 'PARAMETER_PARAM_METADATA'
export const PARAMETER_HEADER_METADATA = 'PARAMETER_HEADER_METADATA'

export const RESPONSE_METADATA = 'RESPONSE_METADATA'

export const INTERCEPTOR_METADATA = 'INTERCEPTOR_METADATA'
export const REGISTER_ADAPTER_METADATA = 'REGISTER_ADAPTER_METADATA'
export const REGISTER_INTERCEPTOR_METADATA = 'REGISTER_INTERCEPTOR_METADATA'

export const LOADBALANCE_SERVICE = 'LOADBALANCED'
