export const CONFIG_PREFIX = 'loadbalance'

export const LOADBALANCE_OPTIONS = Symbol('LOADBALANCE_OPTIONS')

export const LOADBALANCED = 'LOADBALANCED'
export const RULES_METADATA = 'RULES_METADATA'
export const REGISTER_RULES_METADATA = 'REGISTER_RULES_METADATA'
